FROM node
#Consider using the pm2 image https://github.com/dashersw/docker-node-pm2

COPY ./ /client/
#This is a shared host volume used by both client and scrape.
VOLUME /database

#Use this volume to override code with a local copy
VOLUME /client/
RUN npm install pm2 -g

WORKDIR /client
CMD pm2 start process.json --no-daemon
EXPOSE 3000 3000

#docker build -t psjobs_client .
#docker run -v '/database':'/home/nokout/projects/psjobs/database' -P client
