FROM node

COPY ./ /scrape/
VOLUME /database
VOLUME /scrape

WORKDIR /scrape
RUN npm install -g phantomjs && npm install -g casperjs

CMD /scrape/scrape.bash

#Command line follows to help in building compose
#docker build -t psjobs_scrape .
#docker run -v '/database':'/home/nokout/projects/psjobs/database' -P psjobs_scrape
