
FROM node
#not sure if the node docker has cron

COPY .*:/scrape
VOLUME /database

#CMD curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash - && sudo apt-get install -y nodejs
CMD sudo npm install -g casperjs

RUN /scrape/scrape.bash
